---
functional:
  - Требование 3
  - Требование 4
  - Требование 8
  - Требование 9
  - Требование 12
non-functional:
  - Требование 1
  - Требование 2
  - Требование 5
  - Требование 6
  - Требование 7
  - Требование 10
  - Требование 12
  - Требование 13
implicit:
  - Требование 
  - Требование 
  - Требование 
  - Требование 
  - Требование 
  - Требование 
