---
test-cases:
  - summary: |
      Проверка добавления товара в корзину из каталога и корректного пересчета общей стоимости
    status: pass
  - summary: |
      Проверка удаления товаров внутри корзины 
    status: pass
  - summary: |
      Проверка фильтрации товаров по категориям и сортировки по цене
    status: pass
  - summary: |
      Проверка регистрации нового пользователя с валидными данными
    status: pass
bugreports:
  - summary: |
      Несоответствие итоговой стоимости товара в модальном окне успешного оформления заказа
    environment: |
      https://products-store-v2.hexlet.app/, Google Chrome 146.0.7680.177 (официальная сборка) (64 бит) Ubuntu 22.04.5 LTS
    steps-to-reproduce: |
      1. Перейти на сайт https://products-store-v2.hexlet.app/. 
      2. Переключить язык интерфейса приложения на русский (RU). 
      3. Добавить любой товар в корзину (зафиксировать первоначальную стоимость товара). 
      4. Перейти в корзину и нажать кнопку "Checkout".
      5. Обратить внимание на стоимость товара, отображаемую в появившемся модальном окне об успешном создании заказа.
    expected-result: |
      В строке товара отображается его корректная цена, полностью совпадающая с ценой в каталоге и корзине.
    actual-result: |
      В строке товара напротив его наименования отображается завышенная стоимость, хотя итоговая сумма всего заказа может считаться верно.
